"""AGENTIC STAR Marketplace entrypoint — one-shot Pod process.

Generated by agenticstar-deploy's setup_deploy.py. Referenced by
agenticstar-deploy/Dockerfile's `CMD ["python", "cli.py"]`. Compiles the
agent, provisions its secrets, then hands off to
shared.bootstrap.marketplace_app for the Marketplace lifecycle (identity,
input, events, terminal delivery, exit).
"""

from pathlib import Path

from src.graph.graph import SvcC2047StaffingContractComplianceAgent
from framework.utils.config_loader import load_agent_config
from shared.bootstrap.marketplace_app import run_agent_marketplace

# Add config overrides here if needed, instead of editing config/config.yaml.
extend_config = {}

if __name__ == "__main__":
    run_agent_marketplace(
        SvcC2047StaffingContractComplianceAgent,
        agent_name="SVC-C2-047",
        config={**load_agent_config(Path(__file__).resolve().parent), **extend_config},
    )
